### ISSUE TITLE
Errors accumulate in the error popup

### ISSUE THREAD

**Issue by martinos** [rtfeldman/elm-spa-example#1]
If we click multiple times on a like button and we are not logged in, we get multiple errors.

![screen shot 2017-05-08 at 08 56 48](https://cloud.githubusercontent.com/assets/104921/25805084/555964cc-33cc-11e7-8954-05eef80a95c8.jpg)

**Comment by rtfeldman** [comment]
I thought about this, and it seemed more useful to give you more feedback every time you took the action.

(If you wanted to go with the other design, all it would take would be swapping out `errors : List String` for `errors : Set String`)
