### ISSUE TITLE
No error when logging in with the incorrect credentials.

### ISSUE THREAD

**Issue by stil4m** [rtfeldman/elm-spa-example#4]
The app does not provide any feedback when you try to login with incorrect credentials.
It seems that the 422 server response is ignored in the login form.

Encountered on commit: 80fff806980fb9876af7aac8acfd0f990d4c1107

**Comment by andys8** [comment]
If the credentials are wrong, the server responds with `status 422` and the response is:
```json
{"errors":{"email or password":["is invalid"]}}
```

This case is not part of the `errorsDecoder` cases in `Login.elm`.

I will create a quick pull request to solve the issue.

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/elm-spa-example/pull/10 - thanks!
